// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations.Migrations
{
    [DbContext(typeof(RauscherDbContext))]
    [Migration("20250627151717_MigrationInitial")]
    partial class MigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CommodityOpenHighLowClose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Base");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<decimal>("PriceClose")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("PriceClose");

                    b.Property<decimal>("PriceHigh")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("PriceHigh");

                    b.Property<decimal>("PriceLow")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("PriceLow");

                    b.Property<decimal>("PriceOpen")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("PriceOpen");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Symbol");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.ToTable("CommodityOpenHighLowClose", (string)null);
                });

            modelBuilder.Entity("Domain.Models.AboutUs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.ToTable("AboutUs", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ApiCredentials", b =>
                {
                    b.Property<string>("Apikey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ApiKey");

                    b.Property<string>("Apisecrethash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApiSecretHash");

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Isactive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("Lastusedat")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUsedAt");

                    b.HasKey("Apikey");

                    b.ToTable("ApiCredentials", (string)null);
                });

            modelBuilder.Entity("Domain.Models.AppParameters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("CommoditiesApiKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CommoditiesApiKey");

                    b.Property<bool>("CommoditiesApiOn")
                        .HasColumnType("bit")
                        .HasColumnName("CommoditiesApiOn");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContactNumber");

                    b.Property<string>("EmailPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailPassword");

                    b.Property<string>("EmailReceiver")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailReceiver");

                    b.Property<string>("EmailSender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailSender");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InstagramUrl");

                    b.Property<string>("MarketClosingHour")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MarketClosingHour");

                    b.Property<string>("MarketOpeningHour")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MarketOpeningHour");

                    b.Property<int>("MinutesIntervalJob")
                        .HasColumnType("int")
                        .HasColumnName("MinutesIntervalJob");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int")
                        .HasColumnName("SmtpPort");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SmtpServer");

                    b.Property<string>("StripeApiClientKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StripeApiClientKey");

                    b.Property<string>("StripeApiPriceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StripeApiPriceId");

                    b.Property<string>("StripeApiSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StripeApiSecret");

                    b.Property<int>("StripeTrialPeriod")
                        .HasColumnType("int")
                        .HasColumnName("StripeTrialPeriod");

                    b.Property<string>("StripeWebhookSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StripeWebhookSecret");

                    b.Property<string>("WebSiteUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WebSiteUrl");

                    b.Property<string>("WhatsappNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WhatsappNumber");

                    b.Property<string>("YahooFinanceApiKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("YahooFinanceApiKey");

                    b.Property<bool>("YahooFinanceApiOn")
                        .HasColumnType("bit")
                        .HasColumnName("YahooFinanceApiOn");

                    b.HasKey("Id");

                    b.ToTable("AppParameters", (string)null);
                });

            modelBuilder.Entity("Domain.Models.CommoditiesRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("BaseCurrency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Base");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<bool>("Isup")
                        .HasColumnType("bit")
                        .HasColumnName("isUp");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Price");

                    b.Property<string>("SymbolCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SymbolCode");

                    b.Property<long?>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("Timestamp");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Unit");

                    b.Property<decimal?>("Variationprice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("VariationPrice");

                    b.Property<decimal?>("Variationpricepercent")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("VariationPricePercent");

                    b.HasKey("Id");

                    b.HasIndex("SymbolCode");

                    b.ToTable("CommoditiesRate", (string)null);
                });

            modelBuilder.Entity("Domain.Models.EventRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EventDate");

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventDescription");

                    b.Property<string>("EventLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventLink");

                    b.Property<string>("EventLocation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventLocation");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventName");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EventType");

                    b.Property<bool>("Published")
                        .HasColumnType("bit")
                        .HasColumnName("Published");

                    b.HasKey("Id");

                    b.ToTable("EventRegistry", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Folder", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("ICON")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ICON");

                    b.Property<string>("SLUG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SLUG");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.HasKey("ID");

                    b.ToTable("Folder", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUTHOR");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTENT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDATE");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FolderId");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImgUrl");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Language");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLISHEDAT");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit")
                        .HasColumnName("VISIBLE");

                    b.HasKey("Id");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Symbols", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<bool>("Appvisible")
                        .HasColumnType("bit")
                        .HasColumnName("AppVisible");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Code");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FriendlyName");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("SymbolType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SYMBOLTYPE");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vendor");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Symbols", (string)null);
                });

            modelBuilder.Entity("Domain.Models.CommoditiesRate", b =>
                {
                    b.HasOne("Domain.Models.Symbols", "Symbol")
                        .WithMany("CommoditiesRates")
                        .HasForeignKey("SymbolCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("Domain.Models.Symbols", b =>
                {
                    b.Navigation("CommoditiesRates");
                });
#pragma warning restore 612, 618
        }
    }
}
